### ISSUE TITLE
mach-o reloc length != 2

### ISSUE THREAD

**Issue by johnothwolo** [Terraspace/HJWasm#167]
Using the `OFFSET` keyword causes the following ld error:

```
ld: in section __TEXT,__text reloc 0: length != 2 and X86_64_RELOC_SIGNED* not supported file 'test.o' for architecture x86_64
```

Here's an example to reporoduce the code

```
;  test.asm

_printf PROTO, format:PTR BYTE, args:VARARG

.data
fmt DB "Hello %s"
message DB "World", 0ah

.code
_main PROC
    invoke _printf, OFFSET fmt, OFFSET message
    ret
_main ENDP

END
```

**Comment by john-terraspace** [comment]
Have you tried using ADDR instead of OFFSET? I don't have a test setup for Mac/Macho at the moment to check myself.

**Comment by john-terraspace** [comment]
Given the move to ARM based Mac's .. and no access to Mac machines to build/test on I'm closing any support for Mac or Macho outputs.
