### ISSUE TITLE
Non-zero RELA section contents

### ISSUE THREAD

**Issue by ghost** [Terraspace/HJWasm#168]
@Hello71 reported that jwasm-family assemblers (jwasm, asmc, uasm) generate wrong relocation.

See also:
https://sourceforge.net/p/sevenzip/bugs/2338/
https://sourceware.org/pipermail/binutils/2022-April/120428.html

**Comment by john-terraspace** [comment]
I have applied a fix for this in 2.56. I've done some rudimentary testing so-far and the results seem correct. I would appreciate some more testing from other Linux users (not my primary OS).
