### ISSUE TITLE
Instruction encoding with address size override prefix is wrong

### ISSUE THREAD

**Issue by Ringdingcoder** [Terraspace/HJWasm#172]
The following file, when built with `uasm -3 -bin -Fl`

```
	.model	flat
	.code
mov edx, [bp+8]
```

will generate this listing:

```
UASM v2.55, Apr 24 2022, Masm-compatible assembler.

testcase.asm
                                        .model  flat
                                        .code
00000000  678B5008              mov edx, [bp+8]
```

But disassembly of the generated binary gives

```
00000000  678B5008          mov edx,[bx+si+0x8]
```

which is obviously something very different.

**Comment by john-terraspace** [comment]
If you want to generate proper 16bit effective addresses you can use:

`option flat:1`
`.code`
`USE16`
`mov edx, [bp+8]`

or using traditional segment notation:

`.model	flat`
`mycode segment para public use16 'code'`
`assume cs:mycode`
`mov edx, [bp+8]`
`mycode ends`

.code simplified directives are really only for 32bit+

**Comment by Ringdingcoder** [comment]
I actually wanted to generate 32 bit code to see if it works. In other assemblers, it does. The correct binary code would be 678B5608.

**Comment by john-terraspace** [comment]
Ah ok, I'll look into that then.

**Comment by john-terraspace** [comment]
Out of curiosity, is there an actual use-case for this, or more just because you should be able to ?

**Comment by john-terraspace** [comment]
Fixed in 2.56

**Comment by Ringdingcoder** [comment]
Use case, meaning that the assembled code needs to do something useful, no. But meaning, the assembler can be used as a tool for experimentation, absolutely ;). Investigating interesting behavior tends to get harder with the amount of misbehaving links in the chain.

**Comment by john-terraspace** [comment]
Got it 😊 Well it’s all sorted now, if you want to try and let me know then we can close this ticket.

**Comment by Ringdingcoder** [comment]
I verified that this is fixed.
