### ISSUE TITLE
Bad code generated for vpbroadcastd

### ISSUE THREAD

**Issue by bpxhmemcpy** [Terraspace/HJWasm#181]
v2.55

This : 
```asm
vpbroadcastd ymm11,r8d
```
generates bad code:
```asm
C4 42 7D 7C D8
```
instead of:
```asm
62 52 7D 28 7C D8
```

**Comment by john-terraspace** [comment]
Fixing in 2.56
Note from: https://stackoverflow.com/questions/64684140/broadcasting-dword-to-ymm
Oddly, this encoding with an GPR source operand doesn't seem to be specified in the Intel instr. manuals, but is valid. 
The AVX2 codegen now checks and prevents the use of these instructions with a GPR, whilst the new CodegenV2 which handles AVX512 has them added for the EVEX forms.

**Comment by john-terraspace** [comment]
Fixed in 2.56

**Comment by bpxhmemcpy** [comment]
I didn't realize there was a valid EVEX version.
Thanks for the update!

**Comment by john-terraspace** [comment]
Me neither, it doesn't show up in any of the instruction manuals, always helps when the documentation is right.. grr It seems like it's only valid for vpbroadcastd and vpbroadcastq however. It's quite a useful addition I must say, glad to be made aware of it, saves having to do separate data movement and broadcast ops.

**Comment by bpxhmemcpy** [comment]
I tested 2.56 and can confirm this is resolved.
