### ISSUE TITLE
FTBFS with 2.56 on Linux

### ISSUE THREAD

**Issue by grawlinson** [Terraspace/HJWasm#182]
The recent release fails to build on Linux.

I've tried to build with just `dbgcv.c` changes in #161 and it compiles successfully.

On behalf of the greater community, it would be much appreciated if 161 was merged.

**Comment by teoberi** [comment]
The source code from the archive on GitHub (v2.56.tar.gz) does not include those changes, strange!
If you clone version v2.56 from GitHub, it compiles without problems, even if you add the security hardening flags:
-fstack-protector-strong
-D_FORTIFY_SOURCE=2
-pie -fPIE
-Wl,-z,now

**Comment by grawlinson** [comment]
I’ll give that a go, thanks for mentioning it!

**Comment by grawlinson** [comment]
> The source code from the archive on GitHub (v2.56.tar.gz) does not include those changes, strange!
> If you clone version v2.56 from GitHub, it compiles without problems, even if you add the security hardening flags:
> -fstack-protector-strong
> -D_FORTIFY_SOURCE=2
> -pie -fPIE
> -Wl,-z,now

I just cloned `v2.56` locally, and I can't get it to compile due to the same errors as #97 and #148 (`dbgcv.c:20:10: fatal error: direct.h: No such file or directory`) so I'm not sure how you're getting it to compile.

**Comment by teoberi** [comment]
`git clone -b v2.56 https://github.com/Terraspace/UASM.git`

**Comment by teoberi** [comment]
Maybe something is messed in GitHub releases.
The correct one:
https://github.com/Terraspace/UASM/tree/v2.56
The wrong one:
https://github.com/Terraspace/UASM/tree/refs/tags/v2.56

**Comment by john-terraspace** [comment]
The release and tag should be correct now for 2.56.
I will address some of the PRs subsequently for the next release, however I've never had any issues compiling the code as-is on Linux (latest Ubuntu currently) using make -f gccLinux.mak (apart from the untidy warnings).

**Comment by teoberi** [comment]
Correct!
I also had no problems compiling on Slackware 64-current even if I use security hardening flags.

**Comment by grawlinson** [comment]
Thanks for your help, both of you.

I've just pushed an updated version of uasm to the repositories on Arch Linux.
