### ISSUE TITLE
and al, 0F0h – Operans must be the same size 1-4

### ISSUE THREAD

**Issue by sergiou87** [Terraspace/HJWasm#189]
Running UASM x86 (32bit) on Windows for this simple program:
```asm
.386
.model FLAT, C

.CODE

mov al, 0F0h
mov ah, 0F0h
mov ax, 0F0h
mov eax, 0F0h ; this one works

END
```

Results in this:
```
$ uasm -EP -Fo A.ASM.obj A.ASM
.386
.model FLAT, C
.CODE
a.asm(8) : Error A2048: Operands must be the same size: 1 - 4
mov al, 0F0h
a.asm(9) : Error A2048: Operands must be the same size: 1 - 4
mov ah, 0F0h
a.asm(10) : Error A2048: Operands must be the same size: 2 - 4
mov ax, 0F0h
mov eax, 0F0h
END
```

This very same code builds fine on Linux, and it's super weird it thinks 0F0h is 4 bytes. I've tried to change that value and it seems to happen for values of 080h or higher. If I use 07Fh instead, I don't get that error.

Is this a bug in UASM or am I missing something?

**Comment by sergiou87** [comment]
I think the problem was I used a 32bit version of UASM from Mingw. Using the 32bit exe from this repo's releases works as expected. Sorry!

**Comment by Fatemehsale** [comment]
![9a6fe0c8acf8d7280a1b9d0b120ef97d-min](https://user-images.githubusercontent.com/131570543/233829702-c4be5c36-0ae4-4097-97ec-83edffa6263c.jpg)

**Comment by Fatemehsale** [comment]
@![9a6fe0c8acf8d7280a1b9d0b120ef97d-min](https://user-images.githubusercontent.com/131570543/233829702-c4be5c36-0ae4-4097-97ec-83edffa6263c.
jpg)
   @@@``

**Comment by Fatemehsale** [comment]
[Uploading split_config.xhdpi.apk…]()
