### ISSUE TITLE
The state of the project

### ISSUE THREAD

**Issue by mazegen** [Terraspace/HJWasm#203]
The last commit on the master branch is more that 2 years old. Is this project still alive?

**Comment by john-terraspace** [comment]
It’s not dead, at least I’m not.. I’ve just not had time for any side projects over the last year+

I’m hoping to pickup again this year still and at least get another update out with some pressing issues and additional instructions.

 

From: mazegen ***@***.***> 
Sent: Monday, July 15, 2024 12:14 PM
To: Terraspace/UASM ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Terraspace/UASM] The state of the project (Issue #203)

 

The last commit on the master branch is more that 2 years old. Is this project still alive?
