### ISSUE TITLE
Option ZEROLOCALS

### ISSUE THREAD

**Issue by john-terraspace** [Terraspace/HJWasm#28]
Possible feature: with the presence of this option LOCAL values decared in a PROC are automatically initialised to zero?

**Comment by habran** [comment]
Possible feature: with the presence of this option LOCAL values decared in
a PROC are automatically initialised to zero?

that I understand

**Comment by john-terraspace** [comment]
Implemented with OPTION ZEROLOCALS:{0|1}

Generated code will use immediate moves up to a set size at which point it will switch to a more optimal rep stos.

**Comment by habran** [comment]
BTW what do you think about the trails on the bottom of oceans, for example
this:
[image: Inline image 1]

**Comment by john-terraspace** [comment]
?
