### ISSUE TITLE
Support for Delphi Register caling convention

### ISSUE THREAD

**Issue by atelierw** [Terraspace/HJWasm#29]
In 32-bit the Borland/Delphi Register calling convention (this is the default calling convention in Delphi) passes the firsts 3 parameters in registers EAX, EDX and ECX, in this order. Remaining parameters follow the stdcall convention.
I believe this is not a complicated addition and will add significant value and differentiation to HJWASM.

**Comment by habran** [comment]
I haven't switched it in proc.c now, it is done
