### ISSUE TITLE
Add a gitter chat room

### ISSUE THREAD

**Issue by mrfearless** [Terraspace/HJWasm#3]
Create a gitter.im room and display gitter badge on readme.md - useful for discussions and it integrates with github and you can reference issues and commits directly in chat which shows as links back to repo for the issue/commit/pull request/comments

x64dbg uses one, https://github.com/x64dbg/x64dbg

Here is x64dbg's gitter page: [x64dbg gitter](https://gitter.im/x64dbg/x64dbg?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

Users can use a gitter desktop client (windows: http://update.gitter.im/win/latest - mac/linux also available) or web or mobile (iphone/android)

https://gitter.im/

**Comment by john-terraspace** [comment]
Created:

https://gitter.im/john-terraspace/HJWASM
