### ISSUE TITLE
MAN GITIGNORE

### ISSUE THREAD

**Issue by milabs** [Terraspace/HJWasm#30]
Guys, you are missing the basics of git.

How can we port your changes to [JWasm](https://github.com/JWasm/JWasm) if 99% of your's changes is updating of compiler generated object files.

**Comment by john-terraspace** [comment]
The reason we didn't put the gitignore in at present is the team is very small and we're not actively taking remote contributions, so it just made sense for us to leave the repo as a complete dump of the project folder.
I wouldn't be very receptive to having another jwasm fork going.. as all we'd be doing is creating fragmentation. What are you proposing  to port, from and to where? I'd rather get everyone contributing to a single code-base if we have valuable additions to make.

**Comment by john-terraspace** [comment]
If it makes you feel better I've added the updated gitignore and removed tracking of all the build assets.

**Comment by milabs** [comment]
I'm in doubt that it's useful to get `*.obj` files in the repository. Bear in mind cloning performance and diff analyzing. How can one review your's changes without filtering tons of useless information?

As to [that](https://github.com/JWasm/JWasm) fork, it lacks of activity for the moment. Also, it lack of AVX512 support and has some unfixed errors. We had imported all of the original JWasm issues from the sourceforge. Also we had Travis-CI, AppVeyor and Coverity integrated.

Also, we would like to see the purposeful development of the project, not spontaneous, as is happening now. Also, whole the project lacks good regression test coverage. It would be nice to have such tests in addition to the existing.

**Comment by john-terraspace** [comment]
Well up till now, I’m the only one contributing to the repository.. so I don’t have to review any changes :) The advantage of a one-man repository!

But I take your point about the cruft that is floating around in the repo, hence you reminding me I have removed it all.

 

If you want we can import any outstanding jwasm issues into the hjwasm issues log, Travis-CI and Gitter are running already, I haven’t gotten around to setting anything else up for it.

 

I’ve started on updating the regression tests, I have them running locally and have cleaned up about 5 of them. Obviously with the number of changes we’ve made to the source a lot of the binary level regressions and message related ones need updating still. It’s a slow process.

I have a separate repository for the tests at : https://github.com/Terraspace/HJWasmRegression

**Comment by milabs** [comment]
Please, consider to contributing into the [JWasm](https://github.com/JWasm/JWasm) project, not the HJWasm. We have a great community of JWasm users and also we have JWlink sources too. Anyway, here is the correct way to implement some change to the source base: https://github.com/JWasm/JWasm/pull/200
