### ISSUE TITLE
Minor AVX512 issue

### ISSUE THREAD

**Issue by gwoltman** [Terraspace/HJWasm#32]
vmovdqa  zmm1, ZMMWORD PTR abc

does not assemble, but 

vmovdqa  zmm1, YMMWORD PTR abc

does

**Comment by john-terraspace** [comment]
Thanks for spotting these issues, we’ll investigate and sort them out!

**Comment by john-terraspace** [comment]
Can you send me the data declaration for abc ?

 

I’ve tried a few different combinations of this and it appears to work for me.

**Comment by gwoltman** [comment]
Hi,

Thanks for looking into these issues.

"abc" was really ZMM_BITS30 declared as follows:

ZMM_BITS30 DD
3FFFFFFFh,0,3FFFFFFFh,0,3FFFFFFFh,0,3FFFFFFFh,0,3FFFFFFFh,0,3FFFFFFFh,0,3FFFFFFFh,0,3FFFFFFFh,0

Best regards,
George Woltman

**Comment by john-terraspace** [comment]
Hi,

 

We have implemented some changes for this which will be ready either later today or tomorrow.

 

There are some notes however:

 

Technically, there is no instruction vmovdqa zmm(n), … 

Rather only vmovdqa32 or vmovdqa64.

As such we’ve added automatic conversion of the instruction, so vmovdqa zmm(n),MEM with automatically convert to vmovdqa32/64.

 

The ensure proper types however we are forcing the requirement for ZMMWORD type reference.. that means that:

 

       vmovdqa zmm1, ZMMWORD PTR ZMM_BITS30  ;this will work

       ;vmovdqa zmm1, YMMWORD PTR ZMM_BITS30 ;this will fail (Cannot move YMMWORD type to ZMM(n)

       vmovdqa ymm1, YMMWORD PTR YMM_BITS30  ;this will work

       ;vmovdqa zmm1, ZMM_BITS30             ;this will fail  (no ZMMWORD type, source data is DD type)

       ;vmovdqa ymm1, YMM_BITS30             ;this will work

 

Regards,

John

**Comment by john-terraspace** [comment]
Please download the latest package from the site and re-test. This latest build of 2.15 r2 should solve the AVX2, ZMM encoding issues you have had (plus a few more we found!).

 

Regards,

John
