### ISSUE TITLE
Prefix bit or byte warnings

### ISSUE THREAD

**Issue by gwoltman** [Terraspace/HJWasm#34]
HJWASM produces different output than ml64, causing objconv to output messages like below (I can email the full objconv output if all examples are needed):

`; Note: Prefix bit or byte has no meaning in this context`
`        vpmuludq ymm10, ymm9, ymmword ptr [r11+560H]    ; 3A73 _ C4 41 B5: F4. 93, 00000560`

John says this should not be a problem, but....

I'm getting EXC_BAD_INSTRUCTION crashes on Mac OS X.   Now, this could be caused by an incompatibility with objconv.  My build process is to use HJWASM 32-bit on Windows.  Then the object file is fed into objconv to create a Mach-O object file and finally linked on the Mac.

I have confirmed that the ML64 object file works in my build process and the HJWASM object file does not.  I have not yet tried the HJWASM object file linked into a Windows executable.

**Comment by john-terraspace** [comment]
Hi,

 

It would be great if you could provide the full list of ML64 vs. HJWASM differences from objconv, save fixing them piece-wise we can address them all in a batch.

 

Is it possible for you to step through on OSX (via gdb I assume?) and confirm that it is one of these different encoding instructions that cause the bad instruction?

 

I have tried multiple times to get an obj file create on PC (with ml or hjwasm) via obj conv into something runnable on osx and have never succeeded so I am very interested in how you’re getting 

This right!

 

I create a source-base at one point (to include with HJWASM) with some example apps that should compile for windows/linux and osx without any modification save that each OS has a custom lib include, however I gave up due to OSX not playing ball, couldn’t even get a simple console printf type example to work.

**Comment by gwoltman** [comment]
A good night's sleep and some further debugging has narrowed down the
problem.  There are 84 differences between the ML64 and HJWASM output.
This is the one that causes the crash:

HJWASM:
`        vpmovmskb rbx, ymm3                             ; 39A8 _ C4 E1 FC:
D7. DB`
`        vpmovmskb rbx, ymm9                             ; 39B2 _ C4 C1 FC:
D7. D9`

ML64:
`        vpmovmskb rbx, ymm3                             ; 39A8 _ C4 E1 FD:
D7. DB`
`        vpmovmskb rbx, ymm9                             ; 39B2 _ C4 C1 FD:
D7. D9`

Contrary to my earlier bug report this is the only difference in the
objconv output that is NOT preceded by the '; Note: Prefix bit or byte has
no meaning in this context' warning.  So you may well be correct that this
warning message is innocuous.


As to getting a Mac OS X build working, I got lucky and had no trouble
using objconv.  The relevant lines from my makefile:

`masm64=HJWasm32 /c /DX86_64 /DWINDOWS64 /I..\gwnum -win64`
`#masm64=ml64 /c /DX86_64 /DWINDOWS64 /I..\gwnum`
`#masm64=ml64 /c /DX86_64 /DWINDOWS64 /I..\gwnum /Fl /Sf /Sa`
`masm64lx=HJWasm32 /c /DX86_64 /DLINUX64 /I..\gwnum -win64`
`#masm64lx=ml64 /c /DX86_64 /DLINUX64 /I..\gwnum`
`objconv=c:\objconv\objconv`

`linux64\factor64.o: factor64.asm factor64.mac`
`    $(masm64lx) /Folinux64\factor64.obj factor64.asm`
`    $(objconv) -felf64 linux64\factor64.obj linux64\factor64.o`
`    attrib -r linux64\factor64.o`
`    $(objconv) -fmacho64 -nu+ linux64\factor64.obj macosx64\factor64.o`
`    attrib -r macosx64\factor64.o`

The WINDOWS64 and LINUX64 defines control the output of prologue and
epilogue MASM macros.  Basically, I studied the Windows ABI and Linux ABI
docs and created macros that handled the different calling conventions (as
best I understood them).  It is my understanding that HJWASM has builtin
support for the different ABIs and one of my longer-term goals is to ditch
my prologue/epilogue macros in favor of your built-in support.

I'm happy to share source code if that will help you find a solution to
making a working Mac OS X build.

**Comment by john-terraspace** [comment]
Hi,

 

That’s quite interesting, as soon as I’ve got a gap I’ll have another go and getting onto OSX :)

 

In the meantime I have resolved the vpmovmskb issue, I will update the packages this evening.

 

John

**Comment by john-terraspace** [comment]
Hi,

 

The vpmovmskb issue is resolved and the updated packages are available for download from the site. Try that out and let me know how you get on! :)

**Comment by gwoltman** [comment]
It finally works!  Many thanks.

BTW, as far as getting a Mac OS X build working, be aware that my working asm code does not call any OS or C runtime library routines.  In many ways, it is as simple a test case as possible.

**Comment by john-terraspace** [comment]
Excellent! Glad to hear it :)

 

When I was experimenting mine all worked to a point. I’d be very interested to see how you get on once you start calling out to C lib functions and syscall stuff.

Ideally I’d like to get some osx examples into hjwasm samples and eventually support Mach-o output format directly.
