### ISSUE TITLE
AVX-512 assembly issue

### ISSUE THREAD

**Issue by gwoltman** [Terraspace/HJWasm#37]
This line is crashing on Knight's Landing  (output is from objconv):

`        korw    k5, k1, k2                              ; 79A4 _ C5 F0: 45. EA`

I wrote this gcc program:

`int main () {`
`__asm__ volatile (\`
`	"korw %k5, %k1, %k2\n\t");`
`}`

and it works.  Under gdb, the kor instruction compiled as:

`c5 f4 45 d5`

Would SSH access to a Linux Knight's Landing machine be of any use?

**Comment by john-terraspace** [comment]
Juts as a heads up on this one:

 

korw %k5, %k1, %k2 is actualy:

korw k2, k1, k5    which is:

korw k2, k1, k5  

00007ff78bcb1010 C5 F4 45 D5                      korw k2, k1, k5

 

You’d need to reverse the arguments to:

korw %k2,% k1, %k5 to get    C5 F4  45  EA

 

0:  c5 f4 45 ea             korw   k5,k1,k2 is the correct encoding.

**Comment by john-terraspace** [comment]
Update version on the  site now, dated 12th November which should fix the korw.

It now generates:

      korw    k5, k1, k2                              ; 0000 _ C5 F4: 45. EA

 

Which is spot on.

 

Out of interest I discovered the following site which has been super useful in testing:

 

https://defuse.ca/online-x86-assembler.htm#disassembly

 

You can quickly throw in an instruction or machine code and get the opposite, very helpful.

 

I think we might need access to KNL at some point depending on how testing goes if we keep running into problems, but fingers crossed we are nearing the end!

 

This will be the first time any of this AVX512 stuff has actually been put into action on real H/W so that is a fantastic opportunity!

**Comment by gwoltman** [comment]
korw looks like its fixed.  Next up vaddpd.

vaddpd zmm20, zmm17, zmm17

assembles as

vaddpd zmm4, zmm17, zmm17

**Comment by gwoltman** [comment]
Correction - dang backwards gas syntax always messes me up!

vaddpd zmm17, zmm17, zmm20

assembles as

vaddpd zmm17, zmm17, zmm4

**Comment by gwoltman** [comment]
also (in gcc/gas syntax so I don't mess up inverting it):

vmovapd %zmm16,%zmm18

assembles as

vmovapd %zmm0,%zmm18

**Comment by gwoltman** [comment]
Finally,  vmulpd and vdivpd fail the same way as vaddpd.

**Comment by john-terraspace** [comment]
vaddpd zmm17, zmm17, zmm20

       vmovapd zmm16,zmm18

       vmovapd zmm18,zmm16

       vmulpd zmm17, zmm17, zmm20

       vdivpd zmm17, zmm17, zmm20

       

       korw k5, k1, k2

 

 

       vaddpd zmm17, zmm17, zmm10

       vmovapd zmm16,zmm8

       vmovapd zmm18,zmm6

       vmulpd zmm17, zmm17, zmm12

       vdivpd zmm17, zmm17, zmm13

 

Confirmed to produce:

 

000000013f891000 62 E1 F5 40 58 CC                vaddpd                   zmm17, k0, zmm17, zmm4  

 

000000013f891006 62 E1 FD 48 28 C2                vmovapd                  zmm16, k0, zmm2  

 

000000013f89100c 62 E1 FD 48 28 D0                vmovapd                  zmm18, k0, zmm0  

 

000000013f891012 62 E1 F5 40 59 CC                vmulpd                   zmm17, k0, zmm17, zmm4  

 

000000013f891018 62 E1 F5 40 5E CC                vdivpd                    zmm17, k0, zmm17, zmm4  

 

000000013fcb101e 62 C1 F5 40 58 CA                vaddpd                   zmm17, k0, zmm17, zmm10  

 

000000013fcb1024 62 C1 FD 48 28 C0                vmovapd                  zmm16, k0, zmm8  

 

000000013fcb102a 62 E1 FD 48 28 D6                vmovapd                  zmm18, k0, zmm6  

 

000000013fcb1030 62 C1 F5 40 59 CC                vmulpd                   zmm17, k0, zmm17, zmm12  

 

000000013fcb1036 62 C1 F5 40 5E CD                vdivpd                   zmm17, k0, zmm17, zmm13  

 

000000013f89101e C5 F4 45 EA                      korw               k5, k1, k2  

 

 

It appears both dest and second source are correct, so it must be a generic issue mapping first source register when > 15.

 

Will get this fixed asap and revert.

**Comment by john-terraspace** [comment]
They should all be fixed. Packages on the site are updated dated today 13th Nov.

 

John

**Comment by gwoltman** [comment]
All reported AVX-512 assembly issues fixed.  Thanks!
