### ISSUE TITLE
Another AVX-512 issue

### ISSUE THREAD

**Issue by gwoltman** [Terraspace/HJWasm#39]
vfnmadd231pd zmm27, zmm24, zmm23

assembles as

        ` 62 02 BD 40: BC. DF`

which disssembles to:

        `vfnmadd231pd zmm27, zmm24, zmm31 `

**Comment by gwoltman** [comment]
and an AVX2 issue too:

vpsrlq	ymm9, ymm7, [r11]

assembles as:

vpsrlq  ymm9, ymm7, xmmword ptr [rbx]           ; 3BF8 _ C5 45: D3. 0B

**Comment by john-terraspace** [comment]
All these issues are fixed, new version/package on the site dated 14th November.

 

Cheers

John

**Comment by gwoltman** [comment]
A little bit closer each day... 

vpsrlq	ymm9, ymm9, 30

assembles as 

vpsrlq  ymm9, ymm1, 30

**Comment by john-terraspace** [comment]
Goodness.. I hope we’re nearly at the end of them!

 

I really think once this is all 100% we need to put some complete regression tests in, against known binary outputs.

**Comment by john-terraspace** [comment]
Affects the whole rotate/shift group:

 

vpsrlq ymm9, ymm9, 30

000000013FE71000 C5 35 73 D1 1E       vpsrlq      ymm9,ymm1,1Eh  

    69:       vpsllq ymm9, ymm9, 30

000000013FE71005 C5 35 73 F1 1E       vpsllq      ymm9,ymm1,1Eh  

    70:       vpslldq ymm9,ymm9, 30

000000013FE7100A C5 B5 73 F9 1E       vpslldq     ymm9,ymm1,1Eh  

    71:       vpsllw ymm8,ymm9,30

000000013FE7100F C5 3D 71 F1 1E       vpsllw      ymm8,ymm1,1Eh  

    72:       vpslld ymm9, ymm9, 30

000000013FE71014 C5 35 72 F1 1E       vpslld      ymm9,ymm1,1Eh  

    73:       vpsraw ymm9, ymm9, 30

000000013FE71019 C5 35 71 E1 1E       vpsraw      ymm9,ymm1,1Eh  

    74:       vpsrad ymm9,ymm9, 30

000000013FE7101E C5 35 72 E1 1E       vpsrad      ymm9,ymm1,1Eh  

    75:       vpsrldq ymm9, ymm9, 30

000000013FE71023 C5 B5 73 D9 1E       vpsrldq     ymm9,ymm1,1Eh

**Comment by john-terraspace** [comment]
Updated packages on the site. All shift/rotates fixed as per list in last note.

**Comment by john-terraspace** [comment]
We’ve also found an issue with the evex encoded versions:

       vpsrlq ymm1, ymm20, 30                   

       vpsllq ymm1, ymm20, 30                   

       vpslldq ymm1,ymm20, 30

       

 

(Register > 15) Fixing these now.

**Comment by gwoltman** [comment]
Not quite:

vpsrlq	ymm9, ymm7, 3

now assembles as:

vpsrlq  ymm9, ymm15, 3                          ; 3B6F _ C4 C1 B5: 73. D7, 03

**Comment by habran** [comment]
Still working
Will be ready tonight

**Comment by gwoltman** [comment]
All fixed.  Thanks!
