### ISSUE TITLE
AVX-512 Broadcast troubles

### ISSUE THREAD

**Issue by gwoltman** [Terraspace/HJWasm#40]
vbroadcastsd zmm16, QWORD PTR ZMM_FMA_RND_CONST3

will not assemble.

Believe it or not, I do have working AVX-512 code so we are getting close to working out all the kinks that affect me.

Regarding the AMD trouble I was having, I eyeballed the code and found an AVX2 instruction in my FMA code path (Piledriver crash) and an SSE4 instruction in my SSE2 code path (K10 crash).  Consequently, I believe the assembly that is not gcc compatible is not high priority.  GDB users will want full compatibility for correct disassembly and ease of placing breakpoints.

**Comment by john-terraspace** [comment]
We’re addressing that gcc compatibility anyway, knowing it’s there bugs us too :)

I’ll the below one onto the list. I also found a few 16bit instructions which won’t assemble so they’re on the radar too, not that many people care about 16bit unless you’re writing a bootloader ;)

**Comment by john-terraspace** [comment]
Glad to hear we’re finally getting “running” avx512 code! Makes all the pain worth it !

**Comment by john-terraspace** [comment]
Hi, new packages up on the site dated 15th Nov. Should solve all of these issues and a few others we found :)

**Comment by john-terraspace** [comment]
Hi,

 

New version up this morning dated 16th Nov. Fixed another issue with vpslldq.

**Comment by gwoltman** [comment]
Fixed.   Thanks!
