### ISSUE TITLE
More worrisome items

### ISSUE THREAD

**Issue by gwoltman** [Terraspace/HJWasm#42]
Using Nov 20th version.

1)  	vpsraq	ymm15, ymm6, 63		; Create mask for each negative count

is reported as this by gdb disassembly:

vpsrad $0x3f,%ymm6,%ymm15

Note the "d" instead of "q"

2)   	vpsraq	ymm15, ymm8, 63

is reported by gdb as  "(bad)"

3)   	vpandn	ymm14, ymm15, ymm14

is reported by gdb as "(bad)"

I'm using a fairly old binutils, so I've no idea where the problem lies.  Program executes OK.

**Comment by gwoltman** [comment]
and another problem:

	vmovd	xmm14, [r8]		

is assembling as:

	vmovq	xmm14, [r8]

**Comment by john-terraspace** [comment]
This is very strange…

 

Defuse reports it as:

 

Disassembly:

0:  c4 41 f9 6e 30          vmovq  xmm14,QWORD PTR [r8]

Visual studio reports it as:

 

       vmovd  xmm14, [r8]

000000013FFD1000 C4 41 F9 6E 30       vmovd       xmm14,qword ptr [r8]  

 

So which is it you ask..

**Comment by john-terraspace** [comment]
These are now fixed:

 

       vmovd  xmm14, [r8]

       vmovq   xmm12, [r11]

       

       vpsraq ymm15, ymm6, 63

       vpsraq ymm15, ymm8, 63

 

Just putting in error handling for the missing 3rd operand forms like:

       vpaddq ymm1, YMM_FMA_ONE

**Comment by john-terraspace** [comment]
Do you want a version of the exe with these fixes before we publish the update including the 3 operand warning ?

**Comment by gwoltman** [comment]
I'm OK right now -- take your time

**Comment by john-terraspace** [comment]
Version 2.17 is now up, it includes all the fixes you’ve raised. Given the new 3 operand validation there may be a few instructions which need checking, let me know how it goes and we can quickly update any more in the instruction tables.

**Comment by gwoltman** [comment]
This no longer assembles:

	kmovw	edx, k3

**Comment by john-terraspace** [comment]
Fixed now (including kmovb,w,d,q)

 

Regards,

John

**Comment by gwoltman** [comment]
kmovw fixed - thanks.

I'm now having trouble with AVX-512 broadcast, though I'm not confident I have the right syntax:

	vpaddd	zmm14, zmm0, [r8]{1-16}

does not assemble.

**Comment by john-terraspace** [comment]
Try:

 

vpaddd zmm14, zmm0, [r8]{1to16}

 

all the broadcast decorators have a “to” in them rather than a dash.

**Comment by gwoltman** [comment]
Thanks.  All issues resolved!
