### ISSUE TITLE
AVX512 misassembly

### ISSUE THREAD

**Issue by gwoltman** [Terraspace/HJWasm#44]
vpsllvd	zmm15, zmm13, zmm7

assembles as

	vpsllvd	zmm15, zmm13, zmm15

**Comment by gwoltman** [comment]
and in working around that:

	vmovd	[rsi+28], xmm17

is assembling as:

62 e1 fd 08 7e 4e 1c 	vmovq  %xmm17,0xe0(%rsi)

Note:  0xe0 does not equal 28

**Comment by gwoltman** [comment]
and 

vpsllvd	zmm17, zmm13, zmm7

assembles as:

62 c2 15 40 47 cf    	vpsllvd %zmm15,%zmm29,%zmm17

**Comment by john-terraspace** [comment]
Hi,

 

Got these we’ll pick them up and update shortly.

 

John

**Comment by john-terraspace** [comment]
These are fixed and will be updated shortly.

**Comment by john-terraspace** [comment]
Fixed, updated 2.19 package is available.
