### ISSUE TITLE
movq [mem],mmxreg emits incorrect opcode

### ISSUE THREAD

**Issue by sergey-sj** [Terraspace/HJWasm#45]
movq mm0,[eax]; 0F 6F 00 ; ok
movq [eax],mm0; 0F 7E 00 ;  wrong (it's movd, not movq), should be  0F 7F 00  
movd mm0,[eax]; 0F 6E 00 ; ok
movd [eax],mm0; 0F 7E 00 ; ok
movd xmm0,[eax]; 66 0F 6E 00; ok
movd  [eax],xmm0; 66 0F 7E 00; ok
movq xmm0,[eax]; F3 0F 7E 00; ok
movq [eax],mm0; 66 0F D6 00; ok

**Comment by john-terraspace** [comment]
This one is fixed and will be updated shortly.

**Comment by john-terraspace** [comment]
Fixed, updated 2.19 package is available.
