### ISSUE TITLE
pextrw r32,mmxreg,imm8  is not recognized 

### ISSUE THREAD

**Issue by sergey-sj** [Terraspace/HJWasm#46]
.686
.XMM
.MODEL FLAT
.CODE
pinsrw mm0, eax, 0 ; 0F C4 C0 00; ok
pextrw eax, mm0, 0 ;  Error A2049: Invalid instruction operands  
 ; - should be 0F C5 C0 00

pextrw eax, xmm0, 0 ; 66 0F C5 C0 00; ok
pinsrw xmm0, eax, 0 ; 66 0F C4 C0 00; ok

**Comment by john-terraspace** [comment]
This one is fixed and will be updated shortly.

**Comment by john-terraspace** [comment]
Fixed, updated 2.19 package is available.
