### ISSUE TITLE
JMP over a RET with a custom epilogue is incorrect

### ISSUE THREAD

**Issue by sergey-sj** [Terraspace/HJWasm#47]
;Strangely, forward JMP is correct but backward is not.

.386
.MODEL FLAT
.CODE

Proc1 PROC NEAR 
test eax,eax; 85 C0
JNZ @@over ; 75 06 -ok
test eax,eax; 85 C0
JNZ @@ret ; 75 00 -ok
@@ret: 
CLC ; F8
RET ; C3

@@over:
test eax,eax ; 85 C0
JNZ @@ret; 75 FA -ok
test eax,eax ; 85 C0
JNZ @@ret; 75 F6 -ok
Proc1 ENDP

TestEpilogue MACRO procname, flag, parmbytes, localbytes, reglist, userparms
CLC
RET
ENDM

OPTION EPILOGUE:TestEpilogue

Proc2 PROC NEAR
test eax,eax ; 85 C0
JZ @@over; 74 06 - ok
test eax,eax ; 85 C0
JNZ @@ret; 75 00 - ok

@@ret: RET; F8 C3; epilogue ok

@@over:
test eax,eax ; 85 C0
JNZ @@ret ; 75 FE - wrong - makes infinite loop
test eax,eax ; 85 C0
JNZ @@ret; 75 FE - wrong
Proc2 ENDP
END

**Comment by john-terraspace** [comment]
I’ve tested this in ML and it’s fine, as a quick test (and this seems to work for me with hjwasm) can you change the label name from @@ret: to something else?
I used @@xet: and make sure the ret instruction is on it’s own line.

 

Let me know if that solves the issue for you.

**Comment by john-terraspace** [comment]
It seems like the issue is the epilogue macro being run on a line that has a label.

Just moving the ret to it’s own line seems to solve the issue.

 

Please confirm.

**Comment by john-terraspace** [comment]
Confirmed that this behaviour isn't present for normal macros, ONLY the epilogue when on a line with a label.

; Disassembly of file: epi.obj
; Thu Jan 26 20:03:24 2017
; Mode: 32 bits
; Syntax: MASM/ML
; Instruction set: 80386

.386
.model flat

public Proc1
public Proc3
public Proc2


_text   SEGMENT DWORD PUBLIC 'CODE'                     ; section number 1

Proc1   PROC NEAR
        test    eax, eax                                ; 0000 _ 85. C0
        jnz     ?_002                                   ; 0002 _ 75, 06
        test    eax, eax                                ; 0004 _ 85. C0
        jnz     ?_001                                   ; 0006 _ 75, 00
?_001:  clc                                             ; 0008 _ F8
        ret                                             ; 0009 _ C3
Proc1   ENDP

?_002   LABEL NEAR
        test    eax, eax                                ; 000A _ 85. C0
        jnz     ?_001                                   ; 000C _ 75, FA
        test    eax, eax                                ; 000E _ 85. C0
        jnz     ?_001                                   ; 0010 _ 75, F6

Proc3   LABEL NEAR
        test    eax, eax                                ; 0012 _ 85. C0
        jz      ?_004                                   ; 0014 _ 74, 06
        test    eax, eax                                ; 0016 _ 85. C0
        jnz     ?_003                                   ; 0018 _ 75, 00
?_003:  clc                                             ; 001A _ F8
        ret                                             ; 001B _ C3

?_004   LABEL NEAR
        test    eax, eax                                ; 001C _ 85. C0
        jnz     ?_003                                   ; 001E _ 75, FA
        test    eax, eax                                ; 0020 _ 85. C0
        jnz     ?_003                                   ; 0022 _ 75, F6
        ret                                             ; 0024 _ C3

Proc2   PROC NEAR
        test    eax, eax                                ; 0025 _ 85. C0
        jz      ?_006                                   ; 0027 _ 74, 06
        test    eax, eax                                ; 0029 _ 85. C0
        jnz     ?_005                                   ; 002B _ 75, 00
?_005:  clc                                             ; 002D _ F8
        ret                                             ; 002E _ C3
Proc2   ENDP

?_006   LABEL NEAR
        test    eax, eax                                ; 002F _ 85. C0
        jnz     ?_005                                   ; 0031 _ 75, FA
        test    eax, eax                                ; 0033 _ 85. C0
; Note: Function does not end with ret or jmp
        jnz     ?_005                                   ; 0035 _ 75, F6

_text   ENDS

_data   SEGMENT DWORD PUBLIC 'DATA'                     ; section number 2

_data   ENDS

END

**Comment by sergey-sj** [comment]
Ok thanks, so there is a workaround - to place labels on separate lines.

Still there's something wrong with labels declared with a colon - two labels on the same line also don't work 
.CODE
l1: l2: ;Error A2209: Syntax error
l1:: l2: ;Error A2209: Syntax error 

;labels in data segment don't work
.DATA
l1: DB ?; Error A2183: Use of register assumed to ERROR

Labels declared with LABEL are all ok, but they aren't scoped.

**Comment by john-terraspace** [comment]
So the fix is more of a workaround, when using a custom epilogue macro, ensure that the ret is on it's own line without a label preceeding it.
